final Map<String, List<String>> statesByCountry = {
  'Argentina': [
    'Buenos Aires',
    'Chubut',
    'Cordoba',
    'Corrientes',
    'Entre Rios',
    'Jujuy',
    'La Pampa',
    'Mendoza',
    'Misiones',
    'Neuquen',
    'Patagonia',
    'Rio Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Tierra del Fuego',
    'Tucumn'
  ],
  'Australia': [
    'Australian Capital Territory',
    'New South Wales',
    'Northern Territory',
    'Queensland',
    'South Australia',
    'Tasmania',
    'Victoria',
    'Western Australia'
  ],
  'Austria': [
    'Burgenland',
    'Carinthia',
    'Lower Austria',
    'Salzburg',
    'Styria',
    'Tyrol',
    'Upper Austria',
    'Vienna',
    'Vorarlberg'
  ],
  'Belgium': [
    'Antwerpen',
    'Flemish Brabant',
    'Hainaut',
    'Lige',
    'Limburg',
    'Luxembourg',
    'Namur',
    'Oost-Vlaanderen',
    'Walloon Brabant',
    'West-Vlaanderen'
  ],
  'Brazil': [
    'Alagoas',
    'Amap',
    'Amazonas',
    'Bahia',
    'Cear',
    'Distrito Federal',
    'Espirito Santo',
    'Goias',
    'Maranho',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Par',
    'Paraba',
    'Parana',
    'Pernambuco',
    'Piaui',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondonia',
    'Roraima',
    'Santa Catarina',
    'So Paulo',
    'Sergipe',
    'Tocantins'
  ],
  'Canada': [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Territories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Qubec',
    'Saskatchewan',
    'Yukon'
  ],
  'Colombia': [
    'Antioquia',
    'Atlantico',
    'Bolivar',
    'Boyac',
    'Cundinamarca',
    'Magdalena',
    'San Andres and Providencia',
    'Santander',
    'Valle del Cauca'
  ],
  'Denmark': [
    'Bornholm',
    'Copenhagen',
    'Frederiksborg',
    'Funen',
    'North Jutland',
    'Ribe',
    'Ringkjbing',
    'Roskilde',
    'Southern Jutland',
    'Storstrm',
    'Vejle',
    'Viborg',
    'West Zealand',
    'rhus'
  ],
  'Finland': [
    'Etel-Karjala',
    'Etel-Pohjanmaa',
    'Etel-Savo',
    'It-Uudenmaa',
    'Kainuu',
    'Kanta-Hme',
    'Keski-Pohjanmaa',
    'Keski-Suomi',
    'Kymenlaakso',
    'Pirkanmaa',
    'Pohjanmaa',
    'Pohjois-Karjala',
    'Pohjois-Pohjanmaa',
    'Pohjois-Savo',
    'Pijt-Hme',
    'Satakunta',
    'Uudenmaa',
    'Varsinais-Suomi'
  ],
  'France': [
    'Alsace',
    'Aquitaine',
    'Auvergne',
    'Brittany',
    'Burgundy',
    'Centre',
    'Champagne-Ardenne',
    'Corsica',
    'Franche-Comte',
    'French Riviera',
    'Ile-de-France',
    'Languedoc-Roussillon',
    'Limousin',
    'Lorraine',
    'Midi-Pyrenees',
    'Nord-Pas-de-Calais',
    'Normandy - Lower',
    'Normandy - Upper',
    'Pays de la Loire',
    'Picardie',
    'Poitou-Charentes',
    'Provence-Alpes-Cote d',
    'Rhne-Alpes'
  ],
  'Germany': [
    'Baden-Wuerttemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thringen'
  ],
  'India': [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Lakshadweep Islands',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Pondicherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal'
  ],
  'Indonesia': [
    'Bali',
    'Central Java',
    'East Java',
    'Irian Jaya',
    'Jakarta Raya',
    'Kalimantan Barat',
    'Kalimantan Tengah',
    'Kalimantan Timur',
    'Maluku',
    'Nusa Tenggara Barat',
    'Nusa Tenggara Timur',
    'Riau',
    'Sulawesi Utara',
    'Sumatera Barat',
    'Sumatera Utara',
    'West Java',
    'Yogyakarta'
  ],
  'Ireland': [
    'Carlow',
    'Cavan',
    'Clare',
    'Connemara',
    'Cork',
    'Donegal',
    'Dublin',
    'Galway',
    'Kerry',
    'Kildare',
    'Kilkenny',
    'Laois',
    'Leitrim',
    'Limerick',
    'Longford',
    'Louth',
    'Mayo',
    'Meath',
    'Monaghan',
    'Offaly',
    'Roscommon',
    'Shannon',
    'Sligo',
    'Tipperary',
    'Waterford',
    'Westmeath',
    'Wexford',
    'Wicklow'
  ],
  'Italy': [
    'Agrigento',
    'Alessandria',
    'Ancona',
    'Aosta',
    'Arezzo',
    'Ascoli Piceno',
    'Asti',
    'Avellino',
    'Bari',
    'Belluno',
    'Bergamo',
    'Biella',
    'Bologna',
    'Bolzano',
    'Brescia',
    'Cagliari',
    'Campobasso',
    'Caserta',
    'Catania',
    'Chieti',
    'Como',
    'Cosenza',
    'Cremona',
    'Cuneo',
    'Ferrara',
    'Florence',
    'Foggia',
    'Forl-Cesena',
    'Frosinone',
    'Genoa',
    'Gorizia',
    'Grosseto',
    'Imperia',
    'L',
    'La Spezia',
    'Latina',
    'Lecce',
    'Lecco',
    'Livorno',
    'Lodi',
    'Lucca',
    'Macerata',
    'Mantua',
    'Massa-Carrara',
    'Messina',
    'Milan',
    'Modena',
    'Naples',
    'Novara',
    'Nuoro',
    'Oristano',
    'Padua',
    'Palermo',
    'Parma',
    'Pavia',
    'Perugia',
    'Pesaro e Urbino',
    'Pescara',
    'Piacenza',
    'Pisa',
    'Pistoia',
    'Pordenone',
    'Prato',
    'Ragusa',
    'Ravenna',
    'Reggio Calabria',
    'Reggio Emilia',
    'Rieti',
    'Rimini',
    'Rome',
    'Rovigo',
    'Salerno',
    'Sassari',
    'Savona',
    'Siena',
    'Siracusa',
    'Sondrio',
    'Taranto',
    'Teramo',
    'Terni',
    'Trapani',
    'Trento',
    'Treviso',
    'Trieste',
    'Turin',
    'Udine',
    'Varese',
    'Venice',
    'Verbano-Cusio-Ossola',
    'Vercelli',
    'Verona',
    'Vibo Valentia',
    'Vicenza',
    'Viterbo'
  ],
  'Japan': [
    'Aichi',
    'Akita',
    'Aomori',
    'Chiba',
    'Ehime',
    'Fukui',
    'Fukuoka',
    'Fukushima',
    'Gifu',
    'Gunma',
    'Hiroshima',
    'Hokkaido',
    'Hyogo',
    'Ibaraki',
    'Ishikawa',
    'Iwate',
    'Kagawa',
    'Kagoshima',
    'Kanagawa',
    'Kochi',
    'Kumamoto',
    'Kyoto',
    'Mie',
    'Miyagi',
    'Miyazaki',
    'Nagano',
    'Nagasaki',
    'Nara',
    'Niigata',
    'Oita',
    'Okayama',
    'Okinawa',
    'Osaka',
    'Saga',
    'Saitama',
    'Shiga',
    'Shimane',
    'Shizuoka',
    'Tochigi',
    'Tokushima',
    'Tokyo',
    'Tottori',
    'Toyama',
    'Wakayama',
    'Yamagata',
    'Yamaguchi',
    'Yamanashi'
  ],
  'Malaysia': [
    'Johor',
    'Kedah',
    'Kelantan',
    'Kuala Lumpur',
    'Melaka',
    'Negeri Sembilan',
    'Pahang',
    'Penang',
    'Perak',
    'Perlis',
    'Putrajaya',
    'Sabah',
    'Sarawak',
    'Selangor',
    'Terengganu'
  ],
  'Mexico': [
    'Aguascalientes',
    'Baja California Norte',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila',
    'Colima',
    'Distrito Federal',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'Mexico',
    'Michoacan de Ocampo',
    'Morelos',
    'Nayarit',
    'Nuevo Leon',
    'Oaxaca',
    'Puebla',
    'Quertaro',
    'Quintana Roo',
    'San Luis Potos',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz-Llave',
    'Yucatan',
    'Zacatecas'
  ],
  'Netherlands': [
    'Drenthe',
    'Flevopolder',
    'Friesland',
    'Gelderland',
    'Groningen',
    'Limburg',
    'Noord-Brabant',
    'Noord-Holland',
    'Overijssel',
    'Utrecht',
    'Zeeland',
    'Zuid-Holland'
  ],
  'New Zealand': [
    'Auckland',
    'Bay of Plenty',
    'Canterbury',
    'Chatham Islands',
    'Gisborne',
    'Hawkes Bay',
    'Manawatu-Wanganui',
    'Marlborough',
    'Nelson',
    'Northland',
    'Otago',
    'Southland',
    'Taranaki',
    'Tasman',
    'Waikato',
    'Wellington',
    'West Coast'
  ],
  'Norway': [
    'Akershus',
    'Aust-Agder',
    'Buskerud',
    'Finnmark',
    'Hedmark',
    'Hordaland',
    'Mre og Romsdal',
    'Nord-Trondelag',
    'Nordland',
    'Oppland',
    'Oslo',
    'Rogaland',
    'Sogn og Fjordane',
    'Sr-Trndelag',
    'Telemark',
    'Troms',
    'Vest-Agder',
    'Vestfold',
    'stfold'
  ],
  'Philippines': [
    'Bicol Region',
    'Cagayan Valey',
    'Calabarzon',
    'Caraga',
    'Central Luzon',
    'Central Visayas',
    'Cordillera Region',
    'Davao Region',
    'Eastern Visayas',
    'Ilocos Region',
    'Mimaropa',
    'Muslim Mindanao',
    'National Capital Region',
    'Northern Mindanao',
    'Soccsksargen',
    'Western Visayas',
    'Zamboanga Peninsula'
  ],
  'Poland': [
    'Bialystok',
    'Bielsko-Biala',
    'Boleslawiec',
    'Bydgoszcz',
    'Chorzw',
    'Czstochowa',
    'Frombork',
    'Gdansk',
    'Gdynia',
    'Gizycko',
    'Gliwice',
    'Gorzw Wielkopolski',
    'Katowice',
    'Kielce',
    'Komorow',
    'Kostrzyn',
    'Krakow',
    'Lodz',
    'Lomza',
    'Lublin',
    'Myslenice',
    'Nowa Ruda',
    'Olsztyn',
    'Plock',
    'Pozna',
    'Rajszew',
    'Rzeszow',
    'Siemianowice Slaskie',
    'Silesia',
    'Sopot',
    'Swinoujscie',
    'Szczecin',
    'Tarnow',
    'Torun',
    'Warsaw',
    'Wroclaw',
    'Zakopane',
    'Zamosc',
    'Ziebice'
  ],
  'Portugal': [
    'Aveiro',
    'Azores',
    'Baixo Alentejo',
    'Braga',
    'Bragana',
    'Castelo Branco',
    'Coimbra',
    'Douro',
    'Estremadura',
    'vora',
    'Faro',
    'Guarda',
    'Leiria',
    'Lisbon',
    'Madeira',
    'Oeiras',
    'Porto',
    'Santarem',
    'Setubal',
    'Viana do Castelo',
    'Vila Real',
    'Viseu'
  ],
  'Puerto Rico': [
    'Aguadilla',
    'Bayamn',
    'Caguas',
    'Carolina',
    'Cayey',
    'Ceiba',
    'Coamo',
    'Condado',
    'Culebra',
    'Fajardo',
    'Guanica',
    'Hato Rey',
    'Humacao',
    'Juncos',
    'Lares',
    'Mayaguez',
    'Ponce',
    'Rincon',
    'Rio Blanco',
    'Rio Grande',
    'Rio Piedras',
    'San Germn',
    'San Juan',
    'Santurce',
    'Trujillo Alto'
  ],
  'Republic Of Korea': [
    'Chungcheongbuk-do',
    'Chungcheongnam-do',
    'Gangwon-do',
    'Gyeonggi-do',
    'Gyeongsangbuk-do',
    'Gyeongsangnam-do',
    'Jeju-do',
    'Jeollabuk-do',
    'Jeollanam-do'
  ],
  'Russian Federation': [
    'Altai',
    'Bashkortostan',
    'Buryatia',
    'Chechnya',
    'Dagestan',
    'Evenki',
    'Kalmykia',
    'Karelia',
    'Khakassia',
    'Khanty-Mansiysk',
    'Komi',
    'Mari El',
    'Tatarstan',
    'Tuva',
    'Udmurtia'
  ],
  'Singapore': [
    'Central Region',
    'East Region',
    'North Region',
    'Northeast Region',
    'Singapore City Centre',
    'West Region'
  ],
  'Spain': [
    'Alava',
    'Albacate',
    'Alicante',
    'Almera',
    'Avila',
    'Badajoz',
    'Barcelona',
    'Burgos',
    'Caceres',
    'Cadiz',
    'Castellon',
    'Crdoba',
    'Cuenca',
    'Girona',
    'Granada',
    'Guadalajara',
    'Guipuzcoa',
    'Huelva',
    'Huesca',
    'Jaen',
    'La Corua',
    'Las Palmas',
    'Leon',
    'Lerida',
    'Lugo',
    'Mlaga',
    'Orense',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Segovia',
    'Sevilla',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zaragoza'
  ],
  'Sweden': [
    'Blekinge',
    'Dalarna',
    'Gotland',
    'Gvleborg',
    'Halland',
    'Jmtland',
    'Jnkping',
    'Kalmar',
    'Kronoberg',
    'Malmhus',
    'Norrbotten',
    'Skne',
    'Stockholm',
    'Sdermanland',
    'Uppsala',
    'Vrmland',
    'Vsterbotten',
    'Vsternorrland',
    'Vstmanland',
    'Vstra Gtaland',
    'rebro',
    'stergtland'
  ],
  'Switzerland': [
    'Aargau',
    'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden',
    'Basel-Land',
    'Basel-Stadt',
    'Bern',
    'Fribourg',
    'Geneva',
    'Glarus',
    'Graubnden',
    'Jura',
    'Lucerne',
    'Neuchtel',
    'Nidwalden',
    'Schaffhausen',
    'Schwyz',
    'Solothurn',
    'St. Gallen',
    'Thurgau',
    'Ticino',
    'Uri',
    'Valais',
    'Vaud',
    'Zug',
    'Zurich'
  ],
  'Taiwan': [
    'Changhua Hsien',
    'Chiayi Hsien',
    'Chilung Hsien',
    'Hsinchu Hsien',
    'Hualian Hsien',
    'Kaohsiung',
    'Kaohsung Hsien',
    'Nantou Hsien',
    'Pingtung Hsien',
    'Taichung Hsien',
    'Tainan Hsien',
    'Taipei',
    'Taipei Hsien',
    'Taitong Hsien',
    'Taoyuan Hsien',
    'Yunlin Hsien'
  ],
  'Thailand': [
    'Ayutthaya',
    'Bangkok',
    'Buriram',
    'Cha-am',
    'Chachoengsao',
    'Chanthaburi',
    'Chiang Mai',
    'Chiang Rai',
    'Chon Buri',
    'Chumphon',
    'Hat Yai',
    'Hua Hin',
    'Kanchanaburi',
    'Khon Kaen',
    'Krabi',
    'Lampang',
    'Lamphun',
    'Loei',
    'Lopburi',
    'Mae Hong Son',
    'Maha Sarakham',
    'Nakhon Nayok',
    'Nakhon Pathom',
    'Nakhon Ratchasima',
    'Nakhon Sawan',
    'Nakhon Si Thammarat',
    'Nong Khai',
    'Nonthaburi',
    'Pattani',
    'Pattaya City',
    'Phangnga',
    'Phathum Thani',
    'Phayao',
    'Phetchabun',
    'Phetchaburi',
    'Phitsanulok',
    'Phuket',
    'Prachin Buri',
    'Prachuap Khiri Khan',
    'Rayong',
    'Roi Et',
    'Sakon Nakhon',
    'Samut Prakan',
    'Samut Sakhon',
    'Sara Buri',
    'Sattahip',
    'Satun',
    'Songkhla',
    'Sukhothai',
    'Supan Buri',
    'Surat Thani',
    'Tak',
    'Trang',
    'Trat',
    'Ubon Ratchathani',
    'Udon Thani',
    'Uthai Thani',
    'Yala'
  ],
  'United Kingdom': ['England', 'Northern Ireland', 'Scotland', 'Wales'],
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
  ],
};
