// Placeholder for firebase_options.dart
// This file is normally auto-generated by the FlutterFire CLI.
// Replace this with your actual Firebase project config.

class DefaultFirebaseOptions {
  static final currentPlatform = null; // <- Replace with real FirebaseOptions
}
