name: tbp
description: TeamBuild+ Clean Rebuild (Dart-only with REST)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.20.2
  path: ^1.8.3
  firebase_auth_rest: ^2.1.1
  dropdown_search: ^5.0.6
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.prod
